[project]
name = "Squidbot"
version = "0.0.0"

# Optional, adding this will enable direct links from the documentation
# to your source code.
git_repo_url = "https://github.com/squidpie/squidbot/"
git_default_branch = "dev"

[paths]
compile_commands = "targets/compile_commands.json"

[ignore]
paths = [
    "/targets/_deps/",
    "_test.cpp",
    "/usr/include/c++/10",
    "/usr/include/x86_64-linux-gnu/c++/10",
    "/usr/include/c++/10/backward",
    "/usr/include/c++/10/backward",
    "/usr/local/include",
    "/usr/include",
    "/usr/include/x86_64-linux-gnu"
]