# docker-compose.yml
# Copyright (C) 2023
# Squidpie

version: "3.5"
services:
    redis:
        image: redis:7.0.6-alpine
        container_name: squidbot-val-redis
        networks:
           - strauss
        ports:
           - "6379:6379"
           
    txt_cmds:
        volumes:
            - ./tests/txt_cmds/txt_cmds.val.yml:/txt_cmds/txt_cmds.yml

networks:
    strauss:
        name: strauss
        external: false